#!/bin/bash
set -e

PHP_ERROR_REPORTING=${PHP_ERROR_REPORTING:-"E_ALL"}
sed -ri 's/^display_errors\s*=\s*Off/display_errors = On/g' /etc/php/7.0/apache2/php.ini
sed -ri 's/^display_errors\s*=\s*Off/display_errors = On/g' /etc/php/7.0/cli/php.ini
sed -ri "s/^error_reporting\s*=.*$//g" /etc/php/7.0/apache2/php.ini
sed -ri "s/^error_reporting\s*=.*$//g" /etc/php/7.0/cli/php.ini
echo "error_reporting = $PHP_ERROR_REPORTING" >> /etc/php/7.0/apache2/php.ini
echo "error_reporting = $PHP_ERROR_REPORTING" >> /etc/php/7.0/cli/php.ini

#Configure Phalcon and PHP
mkdir -p /etc/php/7.0/mods-available
echo "extension=phalcon.so" > /etc/php/7.0/mods-available/phalcon.ini && \
echo "extension=phalcon.so" > /etc/php/7.0/apache2/conf.d/21-phalcon.ini && \
echo "extension=phalcon.so" > /etc/php/7.0/cli/conf.d/21-phalcon.ini && \
echo "extension=mcrypt.so" > /etc/php/7.0/apache2/conf.d/22-mcrypt.ini && \
echo "extension=mcrypt.so" > /etc/php/7.0/cli/conf.d/22-mcrypt.ini && \
sed -i -e "s/;opcache.enable=0/opcache.enable=1/g" /etc/php/7.0/apache2/php.ini

source /etc/apache2/envvars && exec /usr/sbin/apache2 -DFOREGROUND
